"""Agregar campo codigo a UserReward

Revision ID: 18db7438a0c2
Revises: 
Create Date: 2025-11-23 23:11:35.598206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18db7438a0c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_user_rewards_codigo', ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_rewards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
