"""Agregar puntos historicos para ranking

Revision ID: 82abae51985a
Revises: 18db7438a0c2
Create Date: 2025-11-24 09:50:28.101033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82abae51985a'
down_revision = '18db7438a0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntos_historicos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('puntos_historicos')

    # ### end Alembic commands ###
